### PR TITLE
Update Turkish Language

### PR DESCRIPTION
**Pull request by MertcanGokgoz**
Turkish translation has been updated (It's not over)

TODO
=====

- [x] 100% Completed 
- [x] Just new prototype
- [x] There are some missing translation.
- [x] Has translation errors
- [x] Missing rows
- [x] Has not been tested

I need feedback for testing and fix translation typo

### CODE REVIEW

**Comment by MertcanGokgoz** [comment]
maybe need some translations for feedback, but tested and some problems have been solved(typo)  thanks @Nikeo

**Comment by MertcanGokgoz** [comment]
it's my fault 100% Completed and thanks for info

**Comment by Nikeo** [comment]
I won't be able to load your .po file on wordpress.org because I'm not a native Turkish speaker. I would need you to do it. For that the Turkish translation team has to grant you as Project Editor for the theme. 
If you're OK I will simply need to publish a request here : https://make.wordpress.org/polyglots/

**Comment by MertcanGokgoz** [comment]
Thanks @Nikeo I'm closing PR :+1:

**Comment by Nikeo** [comment]
You're welcome @MertcanGokgoz . But I did not understand if you're ready to upload your .po file on wordpress.org. Do you want to do it?

**Pull request closed without merging**
